### ISSUE TITLE
[BUG] 你的python什么版本啊？我依赖安装不动

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#58]
## Describe the bug
疑似python版本问题导致依赖下载失败

## How To Reproduce
1. 克隆下来 然后 pip install -r requirements.txt --break-system-packages

## Screenshots
![image](https://github.com/user-attachments/assets/9058e28f-e951-4e7c-9597-b825f836cf1f)

## Environment Information 我的环境：
 - Operating System: [Ubuntu 24.04.1 LTS]
 - Python Version: [e.g. Python 3.12.3]

## Additional context
(Add any other context about the problem here.)

**Comment by timerring** [comment]
My test environments are as follows:
```
Environment 1:
- Ubuntu 20.04
- Python 3.8

Environment 2:
- Ubuntu 22.04
- Python 3.10
```
Your error seems to occur in the installation of `blrec`, thus you can refer to [blrec Repository](https://github.com/acgnhiki/blrec?tab=readme-ov-file#%E5%AE%89%E8%A3%85) and try to `pip` it separately.

**Comment by timerring** [comment]
If there are no more questions, I will close this issue tonight.

**Comment by lululutx** [comment]
I didn't make it😭, but close it please。 thx

**Comment by timerring** [comment]
You could offer me detailed logs so that I can figure out the reason. And if it is caused by `blrec`, you can also try to open an issue in [the blrec repository](https://github.com/acgnhiki/blrec).
Btw, this project is not so closely dependent on the blrec and python environment. So if you ain't going to start the uploading process without danmakus. You can use the [`BililiveRecorder`](https://github.com/BililiveRecorder/BililiveRecorder) as a substitue for `blrec`, which is my next step to develop.

**Comment by timerring** [comment]
And I will containerize it as a Docker image and release it as soon as possible.

**Comment by lululutx** [comment]
Thanks again for your enthusiasm, if there is a docker version, I should be able to use it very well 😁👍
